#!/bin/sh

## live-config(7) - System Configuration Components
## Copyright (C) 2006-2015 Daniel Baumann <mail@daniel-baumann.ch>
## Copyright (C) 2015-2017 Paweł Pijanowski <pavroo@onet.eu>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.

## Re-configured for SparkyLinux by pavroo <pavroo@onet.eu>
## Last update 2017/07/10

#set -e

Cmdline ()
{
	# Reading kernel command line
	for _PARAMETER in ${LIVE_CONFIG_CMDLINE}
	do
		case "${_PARAMETER}" in
			live-config.noautologin|noautologin)
				LIVE_CONFIG_NOAUTOLOGIN="true"
				;;

			live-config.nox11autologin|nox11autologin)
				LIVE_CONFIG_NOX11AUTOLOGIN="true"
				;;

			live-config.username=*|username=*)
				LIVE_USERNAME="${_PARAMETER#*username=}"
				;;
		esac
	done
}

Init ()
{
	# Disables both console and graphical autologin.
	case "${LIVE_CONFIG_NOAUTOLOGIN}" in
		true)
			exit 0
			;;
	esac

	# Disables graphical autologin, no matter what mechanism
	case "${LIVE_CONFIG_NOX11AUTOLOGIN}" in
		true)
			exit 0
			;;
	esac

	# Checking if package is installed or already configured
	if [ ! -e /var/lib/dpkg/info/sddm.list ] || \
	   [ -e /var/lib/live/config/sddm ]
	then
		exit 0
	fi

	echo -n " sddm"
}

Config ()
{
	# find session manager name
	if [ -f /usr/share/xsessions/awesome.desktop ]; then
		SESSIONMANAGER="awesome"
	elif [ -f /usr/share/xsessions/bspwm.desktop ]; then
		SESSIONMANAGER="bspwm"
	elif [ -f /usr/share/xsessions/budgie-desktop.desktop ]; then
		SESSIONMANAGER="budgie-desktop"
	elif [ -f /usr/share/xsessions/cde-desktop.desktop ]; then
		SESSIONMANAGER="cde-desktop"
	elif [ -f /usr/share/xsessions/cinnamon.desktop ]; then
		SESSIONMANAGER="cinnamon"
	elif [ -f /usr/share/xsessions/deepin.desktop ]; then
		SESSIONMANAGER="deepin"
	elif [ -f /usr/share/xsessions/enlightenment.desktop ]; then
		SESSIONMANAGER="enlightenment"
	elif [ -f /usr/share/xsessions/fluxbox.desktop ]; then
		if [ -f /usr/share/xsessions/Lumina-DE.desktop ]; then
			SESSIONMANAGER="Lumina-DE"
		else
			SESSIONMANAGER="fluxbox"
		fi
	elif [ -f /usr/share/xsessions/gnome-flashback-metacity.desktop ]; then
		SESSIONMANAGER="gnome-flashback-metacity"
	elif [ -f /usr/share/xsessions/gnome.desktop ]; then
		SESSIONMANAGER="gnome"
	elif [ -f /usr/share/xsessions/i3.desktop ]; then
		SESSIONMANAGER="i3"
	elif [ -f /usr/share/xsessions/icewm-session.desktop ]; then
		SESSIONMANAGER="icewm-session"
	elif [ -f /usr/share/xsessions/jwm.desktop ]; then
		SESSIONMANAGER="jwm"
	elif [ -f /usr/share/xsessions/LXDE.desktop ]; then
		SESSIONMANAGER="LXDE"
	elif [ -f /usr/share/xsessions/lxqt.desktop ]; then
		SESSIONMANAGER="lxqt"
	elif [ -f /usr/share/xsessions/mate.desktop ]; then
		SESSIONMANAGER="mate"
	elif [ -f /usr/share/xsessions/openbox.desktop ] && [ -f /usr/bin/obmenu-generator ]; then
		SESSIONMANAGER="openbox"
	elif [ -f /usr/share/xsessions/pantheon.desktop ]; then
		SESSIONMANAGER="pantheon"
	elif [ -f /usr/share/xsessions/pekwm.desktop ]; then
		SESSIONMANAGER="pekwm"
	elif [ -f /usr/share/xsessions/plasma.desktop ]; then
		SESSIONMANAGER="plasma"
	elif [ -f /usr/share/xsessions/trinity.desktop ]; then
		SESSIONMANAGER="trinity"
	elif [ -f /usr/share/xsessions/wmaker-common.desktop ]; then
		SESSIONMANAGER="wmaker-common"
	elif [ -f /usr/share/xsessions/xfce.desktop ]; then
		SESSIONMANAGER="xfce"
	fi

	if [ ! -e /etc/sddm.conf ]
	then
		exit 0
	fi

	# autologin
	if [ -n "${LIVE_USERNAME}" ]
	then
		sed -i -r -e "s|Session=\$|Session=$SESSIONMANAGER.desktop|" \
			  -e "s|User=\$|User=live|" \
		/etc/sddm.conf
	fi

	# Avoid xinit
	touch /var/lib/live/config/xinit

	# Creating state file
	touch /var/lib/live/config/sddm
}

Cmdline
Init
Config
