#!/bin/sh

## fix sddm configurafion for SparkyLinux by pavroo <pavroo@onet.eu>
## Last update 2022/09/29

if [ -e /usr/bin/sddm ]; then
	echo "" >> /etc/sddm.conf
	echo "[Theme]" >> /etc/sddm.conf
	echo "Current=sparky2" >> /etc/sddm.conf
	echo "CursorTheme=Adwaita" >> /etc/sddm.conf
fi
