#!/bin/sh

## fix sddm configurafion for SparkyLinux by pavroo <pavroo@onet.eu>
## Last update 2021/01/31

echo "" >> /etc/sddm.conf
echo "[Theme]" >> /etc/sddm.conf
echo "Current=sparky" >> /etc/sddm.conf
echo "CursorTheme=Adwaita" >> /etc/sddm.conf
